version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/claude-dashboard
    binary: claude-dashboard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - scripts/tmux-mouse-toggle.sh
      - scripts/tmux-status-bar.sh

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: seunggabi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/seunggabi/claude-dashboard"
    description: "k9s-style TUI for managing Claude Code sessions"
    license: "MIT"
    install: |
      bin.install "claude-dashboard"
      # Install helper scripts to a temporary location for setup to use
      libexec.install "scripts/tmux-mouse-toggle.sh"
      libexec.install "scripts/tmux-status-bar.sh"
    post_install: |
      # Run setup to install scripts and configure tmux
      # Copy scripts from libexec to ~/.local/bin
      home = Dir.home
      local_bin = File.join(home, ".local", "bin")
      FileUtils.mkdir_p(local_bin)

      FileUtils.cp(File.join(libexec, "tmux-mouse-toggle.sh"), File.join(local_bin, "claude-dashboard-mouse-toggle"))
      FileUtils.cp(File.join(libexec, "tmux-status-bar.sh"), File.join(local_bin, "claude-dashboard-status-bar"))
      FileUtils.chmod(0755, File.join(local_bin, "claude-dashboard-mouse-toggle"))
      FileUtils.chmod(0755, File.join(local_bin, "claude-dashboard-status-bar"))

      # Run setup to configure tmux
      system "#{bin}/claude-dashboard", "setup"
    caveats: |
      Setup was automatically run during installation.

      If you need to re-run setup:
        claude-dashboard setup

      This will:
      - Install helper scripts to ~/.local/bin/
      - Configure ~/.tmux.conf for F12 mouse toggle
      - Add status bar with version info

      To start using claude-dashboard:
        claude-dashboard
