version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/claude-dashboard
    binary: claude-dashboard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - scripts/tmux-mouse-toggle.sh
      - scripts/tmux-status-bar.sh

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: seunggabi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/seunggabi/claude-dashboard"
    description: "k9s-style TUI for managing Claude Code sessions"
    license: "MIT"
    install: |
      bin.install "claude-dashboard"
      bin.install "scripts/tmux-mouse-toggle.sh" => "claude-dashboard-mouse-toggle"
      bin.install "scripts/tmux-status-bar.sh" => "claude-dashboard-status-bar"
